### ISSUE TITLE
Improve validity check: treat error messages as invalid

### ISSUE THREAD

**Issue by gittaca** [ropensci/robotstxt#58]
When using a `try(robotstxt::get_robotstxt("domain.tld"))` expression to enable skipping over curl or SSL errors, I'm running into the problem that a subsequent `is_valid_robotstxt(data$get_robotstxt_output)` check treats the error message that was saved, as a valid robots.txt.

To reproduce:

```r
> robotstxt::get_robotstxt("domain.tld")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: domain.tld

> robotstxt::is_valid_robotstxt("Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: domain.tld")
[1] TRUE
```

Would it make sense to explicitly `grepl` for `([Dd]is)?allow:` and `User-agent:` in [is_valid_robotstxt.R](https://github.com/ropensci/robotstxt/blob/06aa0d2162fa8c7b9612c55e2934f977364a8923/R/is_valid_robotstxt.R#L17) to make the check stricter?

Related to #32.

**Comment by petermeissner** [comment]
Hmmmm,...

1.) Don't. "Enable skipping over SSL errors" should not be a task laid upon the shoulders of robotstxt. It's not build for this and will not.
2.) robotstxt::get_robotstxt() does, in your case, not even return a robots.txt file - function execution stops due to the error. So why would you test the error message for validity. It only makes sense to test what was returned by get_robotstxt() but in this case you do not get a return.
3.) I am still thinking about if or if not `"Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: domain.tld"` can be valid robots.txt content ... so far I do not see why not. (Clearly it is not the content of a robots.txt file but I am not sure its forbidden by the specification. Checking for Allow and User-Agent definatly is not enough since robots.txt allows for e.g. empty files and such)

I will give this some more thought but propably will close it within the next days.

**Comment by gittaca** [comment]
> 1.) Don't. "Enable skipping over SSL errors" should not be a task laid upon the shoulders of robotstxt.

True, but on the other hand, it shouldn't abort an analysis run over many domains either ;-) I'm already using [`warn = FALSE` and `ssl_verifypeer = 0`](https://gitlab.com/gittaca/roabots/-/blob/a9dfcdcd0c88a3a1160721eb2efd2f0c500ce623/R/download_robots_txt.R#L4-6), but my analysis still aborts.

> 2.)

As I mentioned, [I'm wrapping it in a `try(…)` to save the raw output into another column](https://gitlab.com/gittaca/roabots/-/blob/a9dfcdcd0c88a3a1160721eb2efd2f0c500ce623/README.Rmd#L62-64) so that iterating over a `Domain` column doesn't abort because of one error. Maybe there's a better approach / pattern?

> 3.) … I am not sure its forbidden by the specification

The [RFC's `3.2 File Format Description`](https://www.robotstxt.org/norobots-rfc.txt) does indeed not seem to be 100% clear about what is forbidden, but as both `User-agent line` and `Allow and Disallow lines` are specified, it should IMHO be clear that some other string that's not a comment should be invalid. At least that's the logic that other validators like http://www.visiospark.com/robots-txt-generator-validator/ (see `Validate This` option) are using.

**Comment by gittaca** [comment]
PS `3.)`: The RFC has a `3.3 Formal Syntax` section which specifies:


    agentline    = "User-agent:" *space agent  [comment] CRLF
    …
    disallowline = "Disallow" ":" *space path [comment] CRLF
    allowline    = "Allow" ":" *space rpath [comment] CRLF

It's in [Backus–Naur form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) which I am not sure how to convert to a reg-ex, but because the tokens `User-agent`, `Disallow` & `Allow` are specified there, they should be [matched here _literally_, instead of only _incidentally_ by `\\w.*`](https://github.com/ropensci/robotstxt/blob/06aa0d2162fa8c7b9612c55e2934f977364a8923/R/is_valid_robotstxt.R#L17).

**Comment by petermeissner** [comment]
> True, but on the other hand, it shouldn't abort an analysis run over many domains either

I am sorry for your frustration. 

But. 

- Your error stems from curl. 
- curl is not able to resolve the url. 
- Therefore it cannot get any robots.txt file so it errors. 
- robots.txt does not know how to handle this error either. Because from the point of permission checking this is undefined territory. Should we assume no robots.txt file exists so everything is fair game? Should we assume everything is forbidden? How should we know when we cannot even identify to which server to connect. We did not get any file we did not even get a valid HTTP status code back. Maybe your internet is broken? Maybe ... We simply do not know enough about all the possibilities to make a reasonable decision. The best we can do is break with error and force you to decide how to handle the problem. 




If you want to the function to not stop you have to provide the assumptions on how to interpret non reachable servers and fortify your code against it. Usually this would be done in a loop via tryCatch but you can also put it in a function like this: 

```r
get_robotstxt_no_stop <- 
  function(d){
    tryCatch(
      expr  = get_robotstxt(d), 
      error = 
        function(e){
          return("User-agent: *\nDisallow: *")
        }
    )
  }

get_robotstxt_no_stop("domain.ltd")
## [1] "User-agent: *\nDisallow: *"

```

... or if you must use purrr for this, this is the proper way should be something like this ...

```r
get_robotstxt_possibly <- 
  purrr::possibly(
    .f        = get_robotstxt, 
    otherwise = "User-agent: *\nDisallow: *" 
  )

get_robotstxt_possibly("domain.ltd")
```

**Comment by petermeissner** [comment]
> It's in Backus–Naur form which I am not sure how to convert to a reg-ex, but because the tokens User-agent, Disallow & Allow are specified there, they should be matched here literally, instead of only incidentally by \\w.*.

I do not think so. [They specification allows for extensions](https://www.robotstxt.org/norobots-rfc.txt):

```
robotstxt    = *blankcomment
                 | *blankcomment record *( 1*commentblank 1*record )
                   *blankcomment
...
record       = *commentline agentline *(commentline | agentline)
                   1*ruleline *(commentline | ruleline)
...
ruleline     = (disallowline | allowline | extension)
...
extension    = token : *space value [comment] CRLF
... 
```

**Comment by gittaca** [comment]
Thanks for pointing out `purr::possibly`!

Still, it's besides the point I'm trying to make. Me wrapping `get_robotstxt` or catching `curl` errors in some suboptimal way does not matter here. That's just context info to this issue.

About `extension`s: yes, sensible ones like `Sitemap` should be matched, of course. However, you're surely not suggesting that `Error in …::…` is a sensible `robots.txt` extension, are you?

I'd like to direct this back to the point: `is_valid_robotstxt()` should not return `TRUE` (IMHO, because of a too lax reg-ex) for a string that not even remotely resembles a line from a `robots.txt` file.

**Comment by petermeissner** [comment]
Sure, let's get back to is_valid_robotstxt() which hopefully returns TRUE if something is a valid robots.txt and FALSE if it is not. 

- First, let's not focus on implementation details (my super clever 'too lax reg-ex' is not to made fun of unless there is a reasonable, valid and robust alternative 🤓 ). Implementation details can be changed if need be but only if we know to what they should be changed to.
- Second, we both agree that `Error in …::…` should not be tagged as valid. 

That being said I think it's very hard to come up with rules that distinguish valid content from invalid. Here are the hard rules (either from the RFC or from de-facto practice) that I know of. 

- empty lines are allowed ✔️ 
- no content is allowed ✔️ 
- content lines have to have a colon separating field names from field value ✔️ 
- field names should be case insensitive ✔️ 

Now, if I am reading the specs right ...

- non ASCII characters are forbidden for field names 
- special characters are forbidden for field names: `( ) < > @ , ; : \ < > / [ ] ? = { } SP HT` 
- field values can be any ASCII character (meaning that special characters forbidden in field names are allowed here!)

... now from this I think I can add a check that check that if a line looks like field-name:field-value that no special character is included before the first colon (:) this would indeed rule out the error message - which triggered the debate - since there are spaces before the first colon (:). 

This certainly would make `is_valid_robotstxt()` a better check. Still, it leaves room for plenty of content that passes as valid although it's clearly not for the human eye.

**Comment by petermeissner** [comment]
Side note ... 

> Still, it's besides the point I'm trying to make.

Jip. But if there are several distinct problems within one issue chances are high several problems will be discussed in whatever order instead of the most central to the problem or the one one might be most interested in.

🤷

**Comment by petermeissner** [comment]
I will push a fix for the problem. It will check that ...

- **special characters are forbidden for field names**: `( ) < > @ , ; : \ < > / [ ] ? = { } SP HT`
- **but it will not check the ASCII requirement** by default (it turns out that Wikipedia does use UTF-8 encoded URLs in its robots.txt file) which makes me very hesitant to be too strict on this spec in the RFC (proposal). Also the Google spec does state that robots.txt should be expected to be UTF-8 although URLs should be URLencoded and thus only consist of ASCII
